name: 'Pipenv for Github Actions'
description: 'Use pipenv commands in your GitHub Actions Workflow.'

inputs:
  command:
    description: 'pipenv command and its argument to be executed'
    required: true 
  working-directory:
    description: 'working directory'
    required: false 
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    WORKING_DIRECTORY: ${{ inputs.working-directory }}
  args:
    - ${{ inputs.command }}

branding:
  icon: 'package'
  color: 'green'
